AM.UI.Web/Models/ErrorViewModel.cs
namespace AM.UI.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AM.UI.Web/Controllers/FlightController.cs
using AM.ApplicationCore.Domain;
using AM.ApplicationCore.Interfaces;
using AM.ApplicationCore.Services;
using AM.Infrastructure;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AM.UI.Web.Controllers
{
    public class FlightController : Controller
    {
        IServiceFlight sf;
        IServicePlane sp;
        public FlightController(IServiceFlight sf,IServicePlane sp)
        {
            this.sf = sf;  
            this.sp = sp;
        }
        // GET: FlightController
        public ActionResult Index(DateTime? dateDepart)
        {
            if (dateDepart == null)
                return View(sf.GetMany());
            else
              return  View(sf.GetMany(f => f.FlightDate.Equals(dateDepart)));
        }

        public ActionResult Sort()
        { 
            return View(sf.SortFlights()); 
        }

        // GET: FlightController/Details/5
        public ActionResult Details(int id)
        {
            return View(sf.GetById(id));
        }

        // GET: FlightController/Create
        public ActionResult Create()
        {
            ViewBag.lsPlanes = new SelectList(sp.GetMany(),"PlaneId","Information");
            return View();
        }

        // POST: FlightController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Flight collection,IFormFile airlineIMG)
        {
            try
            {
                
                if (airlineIMG != null)
                {
                    //sauvegarder le nom du fichier dans la collection
                    collection.AirlineLogo = airlineIMG.FileName;
                    //sauvegarder l'image daqns le dossier uploads
                    var path = Path.Combine(Directory.GetCurrentDirectory(),
                    "wwwroot", "uploads", airlineIMG.FileName);
                    Stream stream = new FileStream(path, FileMode.Create);
                    airlineIMG.CopyTo(stream);
                    
                }

                sf.Add(collection);
                sf.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FlightController/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.lsPlanes = new SelectList(sp.GetMany(), "PlaneId", "Information");

            return View(sf.GetById(id));
        }

        // POST: FlightController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Flight collection)
        {
            try
            {
                sf.Update(collection);
                sf.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FlightController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(sf.GetById(id));
        }

        // POST: FlightController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                sf.Delete(sf.GetById(id));
                sf.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AM.UI.Web/Controllers/HomeController.cs
using AM.UI.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AM.UI.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AM.UI.Web/Controllers/PlaneController.cs
using AM.ApplicationCore.Domain;
using AM.ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AM.UI.Web.Controllers
{
    public class PlaneController : Controller
    {
        IServicePlane sp;
        public PlaneController(IServicePlane sp)
        {
                this.sp=sp;
        }
        // GET: PlaneController
        public ActionResult Index()
        {
            return View(sp.GetMany());
        }

        // GET: PlaneController/Details/5
        public ActionResult Details(int id)
        {
            return View(sp.GetById(id));
        }

        // GET: PlaneController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PlaneController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Plane collection)
        {
            try
            {
                sp.Add(collection);
                sp.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PlaneController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PlaneController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PlaneController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PlaneController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AM.UI.Web/Views/Flight/Create.cshtml
@model AM.ApplicationCore.Domain.Flight

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Flight</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="AirlineLogo" class="control-label"></label>
                <input type="file" name="airlineIMG" asp-for="AirlineLogo" class="form-control" />
                <span asp-validation-for="AirlineLogo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlightDate" class="control-label"></label>
                <input asp-for="FlightDate" class="form-control" />
                <span asp-validation-for="FlightDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstimatedDuration" class="control-label"></label>
                <input asp-for="EstimatedDuration" class="form-control" />
                <span asp-validation-for="EstimatedDuration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EffectiveArrival" class="control-label"></label>
                <input asp-for="EffectiveArrival" class="form-control" />
                <span asp-validation-for="EffectiveArrival" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Departure" class="control-label"></label>
                <input asp-for="Departure" class="form-control" />
                <span asp-validation-for="Departure" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Destination" class="control-label"></label>
                <input asp-for="Destination" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaneFk" class="control-label"></label>
                <select asp-for="PlaneFk" asp-items="ViewBag.lsPlanes" class="form-control"></select>
                <span asp-validation-for="PlaneFk" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AM.UI.Web/Views/Flight/Delete.cshtml
@model AM.ApplicationCore.Domain.Flight

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Flight</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlightId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlightId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AirlineLogo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AirlineLogo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlightDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlightDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstimatedDuration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstimatedDuration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EffectiveArrival)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EffectiveArrival)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Departure)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Departure)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaneFk)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaneFk)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AM.UI.Web/Views/Flight/Details.cshtml
@model AM.ApplicationCore.Domain.Flight

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Flight</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlightId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlightId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AirlineLogo)
        </dt>
        <dd class = "col-sm-10">
            <img src="~/uploads/@Model.AirlineLogo" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlightDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlightDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstimatedDuration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstimatedDuration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EffectiveArrival)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EffectiveArrival)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Departure)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Departure)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaneFk)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaneFk)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

AM.UI.Web/Views/Flight/Edit.cshtml
@model AM.ApplicationCore.Domain.Flight

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Flight</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FlightId" class="control-label"></label>
                <input asp-for="FlightId" class="form-control" />
                <span asp-validation-for="FlightId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AirlineLogo" class="control-label"></label>
                <input asp-for="AirlineLogo" class="form-control" />
                <span asp-validation-for="AirlineLogo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlightDate" class="control-label"></label>
                <input asp-for="FlightDate" class="form-control" />
                <span asp-validation-for="FlightDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstimatedDuration" class="control-label"></label>
                <input asp-for="EstimatedDuration" class="form-control" />
                <span asp-validation-for="EstimatedDuration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EffectiveArrival" class="control-label"></label>
                <input asp-for="EffectiveArrival" class="form-control" />
                <span asp-validation-for="EffectiveArrival" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Departure" class="control-label"></label>
                <input asp-for="Departure" class="form-control" />
                <span asp-validation-for="Departure" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Destination" class="control-label"></label>
                <input asp-for="Destination" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaneFk" class="control-label"></label>
                <select asp-for="PlaneFk" asp-items="ViewBag.lsPlanes" class="form-control" ></select>
                <span asp-validation-for="PlaneFk" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AM.UI.Web/Views/Flight/Index.cshtml
@model IEnumerable<AM.ApplicationCore.Domain.Flight>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>
<form asp-action="index">
    <fieldset>
        <legend> Recherche</legend>
        Saisir une date de départ :
        <input type="date" name="dateDepart" />
        <input type="submit" value="Serach" />
        <input type="submit" value="Sort" asp-action="Sort" />
    </fieldset>
</form>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FlightId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AirlineLogo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstimatedDuration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EffectiveArrival)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Departure)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Destination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlaneFk)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FlightId)
            </td>
            <td>
                <img src="~/uploads/@item.AirlineLogo" width="50" height="50" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FlightDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstimatedDuration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EffectiveArrival)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Departure)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Destination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlaneFk)
            </td>
            <td>
@*                 @Html.ActionLink("Edit", "Edit", new { id=item.FlightId}) |
 *@            
            <a asp-action="Edit" asp-route-id="@item.FlightId">Edit</a>
                @Html.ActionLink("Details", "Details", new {  id=item.FlightId  }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.FlightId  })
                <a asp-controller="Plane" asp-action="Details" asp-route-id="@item.PlaneFk">PlaneDet</a>
            </td>
        </tr>
}
    </tbody>
</table>

AM.UI.Web/Views/Flight/Sort.cshtml
@model IEnumerable<AM.ApplicationCore.Domain.Flight>

@{
    ViewData["Title"] = "Sort";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Sort</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FlightId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AirlineLogo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstimatedDuration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EffectiveArrival)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Departure)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Destination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlaneFk)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FlightId)
            </td>
            <td>
                    <img src="~/uploads/@item.AirlineLogo" width="50" height="50" />
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.FlightDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstimatedDuration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EffectiveArrival)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Departure)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Destination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlaneFk)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

AM.UI.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AM.UI.Web/Views/Plane/Create.cshtml
@model AM.ApplicationCore.Domain.Plane

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Plane</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufactureDate" class="control-label"></label>
                <input asp-for="ManufactureDate" class="form-control" />
                <span asp-validation-for="ManufactureDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaneType" class="control-label"></label>
                <select asp-for="PlaneType" asp-items="Html.GetEnumSelectList<AM.ApplicationCore.Domain.PlaneType>()" class="form-control"></select>
                <span asp-validation-for="PlaneType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Information" class="control-label"></label>
                <input asp-for="Information" class="form-control" />
                <span asp-validation-for="Information" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AM.UI.Web/Views/Plane/Details.cshtml
@model AM.ApplicationCore.Domain.Plane

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Plane</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaneId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaneId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManufactureDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManufactureDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaneType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaneType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Information)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Information)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

AM.UI.Web/Views/Plane/Index.cshtml
@model IEnumerable<AM.ApplicationCore.Domain.Plane>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PlaneId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Capacity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ManufactureDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlaneType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Information)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PlaneId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Capacity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ManufactureDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlaneType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Information)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

AM.UI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AM.UI.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AM.UI.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AM.UI.Web</a>
                <a asp-action="Index" asp-controller="Flight" >IndexFlight</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AM.UI.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>